API_URL = 'https://i.instagram.com/api/v1'
FETCH_URL = f'{API_URL}/si/fetch_headers/?challenge_type=signup&guid='
LOGIN_URL = f'{API_URL}/accounts/login/'
LOGOUT_URL = f'{API_URL}/accounts/logout/'
SYNC_URL = f'{API_URL}/qe/sync/'
USER_LIST_URL = f'{API_URL}/friendships/autocomplete_user_list'
TIMELINE_URL = f'{API_URL}/feed/timeline/'
INBOX_URL = f'{API_URL}/news/inbox/'
USER_INFO_URL = f'{API_URL}/users/%d/info/'
FRIENDSHIPS_URL = f'{API_URL}/friendships/%s/%d/'
UPLOAD_IMG_URL = f'{API_URL}/upload/photo/'
EXPOSE_URL = f'{API_URL}/qe/expose/'
IMG_CONFIGURE_URL = f'{API_URL}/media/configure/'

